- name: Install K3s on Master and Worker Nodes
  hosts: all
  become: yes
  tasks:
    - name: Check if K3s is already installed
      command: which k3s
      register: k3s_installed
      ignore_errors: yes
      changed_when: false

- name: Install K3s on Master Node
  hosts: master
  become: yes
  tasks:
    - name: Install K3s if not installed
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure .kube directory exists for vagrant user
      file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Copy K3s config to vagrant user
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: '0600'

    - name: Retrieve K3s node token
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token

    - name: Store K3s token for worker nodes
      copy:
        content: "{{ k3s_token['content'] | b64decode }}"
        dest: /vagrant/token
        owner: vagrant
        group: vagrant
        mode: '0600'

- name: Install K3s on Worker Nodes
  hosts: workers
  become: yes
  tasks:
    - name: Check if token file exists
      stat:
        path: /vagrant/token
      register: token_file

    - name: Read token from master
      slurp:
        src: /vagrant/token
      register: k3s_token
      delegate_to: k3s-master
      run_once: yes
      when: token_file.stat.exists

    - name: Install K3s worker if not installed
      shell: "curl -sfL https://get.k3s.io | K3S_URL=https://192.168.33.10:6443 K3S_TOKEN={{ k3s_token['content'] | b64decode | trim }} sh -"
      args:
        creates: /usr/local/bin/k3s
      when: token_file.stat.exists
